### ISSUE TITLE
[Issue/Bug] RCS / AIMBot / TriggerBot not working

### ISSUE THREAD

**Issue by LauraSavall** [Nocture-Insight/Dexterion#63]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Dexterion version: v2.1.0 as 2.2.1 show me "counter strike found (%d)"
- Describe install method of offsets: Direct Download from a2x repo's

We were talking about https://github.com/a2x/cs2-dumper/issues/209#issuecomment-2290085898
```

### 📝 Description

Nothing to add, RCS / AIMBot / TriggerBot not working

### ⚙️ Configuration Files

[config.json](https://github.com/user-attachments/files/16620065/config.json)

**Comment by LauraSavall** [comment]
MB v2.2.1 self crash at start

**Comment by wqq-z** [comment]
CS2 updated offsets issue.

**Comment by wqq-z** [comment]
Now should be fixed

**Comment by LauraSavall** [comment]
But got the new *.json and still not working :/ by A2X github

**Comment by wqq-z** [comment]
Hmm, ill see the tomorow (its late btw ) it was working for me the last realese. i think this should be fixed for the next update

**Comment by wqq-z** [comment]
> But got the new *.json and still not working :/ by A2X github

Well, last realese i had auto-tested it all working however some esp func is not working.

**Comment by LauraSavall** [comment]
Totally fine, I'm dumb, my updateoffset was :
curl https://raw.githubusercontent.com/a2x/cs2-dumper/blob/main/output/buttons.json > buttons.json
curl https://raw.githubusercontent.com/a2x/cs2-dumper/blob/main/output/client.dll.json > client.dll.json
curl https://raw.githubusercontent.com/a2x/cs2-dumper/blob/main/output/offsets.json > offsets.json

.........
